In [1]:
#pip install langchain 

In [2]:
from langchain.document_loaders import TextLoader 

In [3]:
loader=TextLoader('nvda_news_1.txt')
data=loader.load()

In [4]:
#pip install -U langchain-community

In [5]:
#To obtain the source link of the notebook 
data[0].metadata

{'source': 'nvda_news_1.txt'}

In [6]:
from langchain.document_loaders.csv_loader import CSVLoader

In [7]:
loader=CSVLoader('movies.csv',source_column="title")
data=loader.load()

In [8]:
data[1].metadata

{'source': 'Doctor Strange in the Multiverse of Madness', 'row': 1}

In [9]:
data[0].page_content

'movie_id: 101\ntitle: K.G.F: Chapter 2\nindustry: Bollywood\nrelease_year: 2022\nimdb_rating: 8.4\nstudio: Hombale Films\nlanguage_id: 3\nbudget: 1\nrevenue: 12.5\nunit: Billions\ncurrency: INR'

In [10]:
#pip install unstructured libmagic python-magic python-magic-bin 

In [11]:
from langchain.document_loaders import UnstructuredURLLoader

In [12]:
loader = UnstructuredURLLoader(
    urls = [
        "https://www.moneycontrol.com/news/business/banks/hdfc-bank-re-appoints-sanmoy-chakrabarti-as-chief-risk-officer-11259771.html",
        "https://www.moneycontrol.com/news/business/markets/market-corrects-post-rbi-ups-inflation-forecast-icrr-bet-on-these-top-10-rate-sensitive-stocks-ideas-11142611.html"
    ]
)

In [13]:
data=loader.load()
len(data)

2

In [14]:
data[0].metadata

{'source': 'https://www.moneycontrol.com/news/business/banks/hdfc-bank-re-appoints-sanmoy-chakrabarti-as-chief-risk-officer-11259771.html'}

In [15]:
text = """Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan. 
It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine. 
Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.

Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007 and was originally set to be directed by Steven Spielberg. 
Kip Thorne, a Caltech theoretical physicist and 2017 Nobel laureate in Physics,[4] was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar. 
Cinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles. 
Interstellar uses extensive practical and miniature effects, and the company Double Negative created additional digital effects.

Interstellar premiered in Los Angeles on October 26, 2014. In the United States, it was first released on film stock, expanding to venues using digital projectors. The film received generally positive reviews from critics and grossed over $677 million worldwide ($715 million after subsequent re-releases), making it the tenth-highest-grossing film of 2014. 
It has been praised by astronomers for its scientific accuracy and portrayal of theoretical astrophysics.[5][6][7] Interstellar was nominated for five awards at the 87th Academy Awards, winning Best Visual Effects, and received numerous other accolades."""

In [16]:
text[:200]

'Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan. \nIt stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Mat'

In [17]:
words = text.split(" ")
chunks=[]
s=""
for word in words : 
    s += word  + " " 
    if len(s)>200: 
        chunks.append(s)
        s= ""

chunks.append(s)

In [18]:
from langchain.text_splitter import CharacterTextSplitter 
splitter=CharacterTextSplitter(
    separator="\n", 
    chunk_size=200, 
    chunk_overlap=0
)
chunks=splitter.split_text(text)

Created a chunk of size 210, which is longer than the specified 200
Created a chunk of size 208, which is longer than the specified 200
Created a chunk of size 358, which is longer than the specified 200


In [19]:
len(chunks)


9

In [20]:
for chunk in chunks : 
    print(len(chunk))

105
120
210
181
197
207
128
357
253


In [21]:
from langchain.text_splitter import RecursiveCharacterTextSplitter 
r_splitter=RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n", " "], 
    chunk_size=200, 
    chunk_overlap=0
)
chunks = r_splitter.split_text(text)

In [22]:
for chunk in chunks : 
    print(len(chunk))

105
120
199
10
181
197
198
8
128
191
165
198
54


In [23]:
chunks=text.split("\n\n")
for chunk in chunks : 
    print(len(chunk))

439
719
612


In [24]:
chunks[1]

'Brothers Christopher and Jonathan Nolan wrote the screenplay, which had its origins in a script Jonathan developed in 2007 and was originally set to be directed by Steven Spielberg. \nKip Thorne, a Caltech theoretical physicist and 2017 Nobel laureate in Physics,[4] was an executive producer, acted as a scientific consultant, and wrote a tie-in book, The Science of Interstellar. \nCinematographer Hoyte van Hoytema shot it on 35 mm movie film in the Panavision anamorphic format and IMAX 70 mm. Principal photography began in late 2013 and took place in Alberta, Iceland, and Los Angeles. \nInterstellar uses extensive practical and miniature effects, and the company Double Negative created additional digital effects.'

In [25]:
first_split=chunks[0]
first_split=first_split.split("\n") 

In [26]:
first_split

['Interstellar is a 2014 epic science fiction film co-written, directed, and produced by Christopher Nolan. ',
 'It stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Matt Damon, and Michael Caine. ',
 'Set in a dystopian future where humanity is embroiled in a catastrophic blight and famine, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humankind.']

In [27]:
second_split=chunks[1]
second_split=second_split.split(" ")

In [28]:
#pip install faiss-cpu 

In [29]:
#pip install sentence-transformers 

In [30]:
import pandas as pd 
pd.set_option('display.max_colwidth', 100)

In [31]:
df=pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [32]:
df 

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [33]:
from tensorflow import keras 
from sentence_transformers import SentenceTransformer 
encoder=SentenceTransformer("all-mpnet-base-v2",use_auth_token='*')
vectors=encoder.encode(df.text)

C:\Users\hp\anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py:193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v4 of SentenceTransformers.
  warnings.warn(


In [34]:
#pip install tensorflow

In [35]:
vectors 

array([[-0.00247392,  0.03626726, -0.05290463, ..., -0.09152359,
        -0.03970003, -0.04330489],
       [-0.03357269,  0.00980513, -0.03250129, ..., -0.05165462,
         0.02245887, -0.03156186],
       [-0.01865323, -0.04051303, -0.01235385, ...,  0.00610585,
        -0.07179644,  0.0277385 ],
       ...,
       [-0.00066465,  0.04252126, -0.05645507, ...,  0.01315469,
        -0.03183566, -0.04357661],
       [-0.03317156,  0.03252455, -0.02484838, ...,  0.01174424,
         0.05747128,  0.0057102 ],
       [-0.00166396,  0.00413831, -0.04597082, ...,  0.02008522,
         0.05656243, -0.00161596]], dtype=float32)

In [36]:
dim=vectors.shape[1]

In [37]:
import faiss 
index=faiss.IndexFlatL2(dim)
index 

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002C3E07318F0> >

In [38]:
#pip uninstall tensorflow keras

In [39]:
index.add(vectors)
index 

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002C3E07318F0> >

In [40]:
#search_query="I want to buy a polo t-shirt"
search_query="One apple per day keep the doctor away"
vec=encoder.encode(search_query)
vec.shape

(768,)

In [41]:
import numpy as np 
svec=np.array(vec).reshape(1,-1)

In [42]:
svec

array([[ 1.82464644e-02,  4.56874371e-02, -1.72905847e-02,
         1.13802189e-02,  1.70955528e-02, -3.17502990e-02,
        -5.43684661e-02,  6.58321008e-03,  3.52204405e-02,
         4.46322002e-02,  7.39289001e-02, -4.68120351e-03,
        -3.98395173e-02,  2.50967741e-02, -3.17743979e-02,
         4.43712473e-02,  4.92172390e-02,  1.26417552e-04,
        -4.64612851e-03, -2.85965819e-02, -1.47376768e-02,
         1.22301010e-02,  1.81759223e-02,  1.69014521e-02,
        -2.66286433e-02, -1.35686491e-02,  6.81273565e-02,
         3.60697135e-02,  8.34500231e-03, -5.60822450e-02,
        -3.91795523e-02, -4.69662203e-03, -6.93685710e-02,
        -2.58666594e-02,  1.55797352e-06,  1.34867541e-02,
         2.16922443e-02,  2.02701613e-02, -4.78109084e-02,
         2.38966215e-02, -2.19338667e-02, -1.01929203e-01,
         8.73351935e-03, -6.70317421e-03, -9.64833703e-03,
         3.27633545e-02, -1.56507008e-02,  3.99133675e-02,
         1.15251187e-02,  5.60248792e-02, -3.12342891e-0

In [43]:
distances,I=index.search(svec,k=2)

In [44]:
#So then we have to compare those two things below : 

In [45]:
# Our search query is "I want to buy a polo t-shirt" wich is related to fashion 

In [46]:
distances 

array([[1.3252231, 1.7418259]], dtype=float32)

In [47]:
I

array([[1, 0]], dtype=int64)

In [52]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health

In [49]:
#Semantic search : to look for it later 

In [50]:
#pip install tensorflow==2.12

In [ ]:
#then we will use retreverial to create prompts 

In [ ]:
#for every chunk we will create a llm then a filtred chunk 

In [ ]:
#the summary of chunks will be used to create the summary chunk 

In [51]:
#pip install -U sentence-transformers